# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 80%  # NFR11 requirement - matches CI threshold
        threshold: 2%  # Allow 2% fluctuation before failing
    patch:
      default:
        target: 80%  # New code should meet same coverage target

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # Only comment if coverage changes
